# Note: ExternalSecret for ESO is known as CRD (Custom Resource Definition) 
# as this is not standard kubernetes resources

#ESO ExternalSecret for aws parameterstore
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: enterprise-rag-envfile
  namespace: enterprise-rag
  labels:
    app: enterprise-rag

spec:
  refreshInterval: 1h

  secretStoreRef:
    #This name should match with ClusterSecretStore for aws-parameterstore
    name: enterprise-rag-aws-parameterstore 
    kind: ClusterSecretStore

  target:
    #This name should match with the one used in "configMapRef" in deployment.yaml 
    name: enterprise-rag-envfile

    #template defines how the final Kubernetes Secret/ConfigMap should be rendered 
    #This can be ignored for simple cases. Without template, ESO directly maps values
    template:
      engineVersion: v2
      data:
        #This means take fetched value APP_ENV and create final key-value pair as APP_ENV=<actual value>
        #Its useful for: renaming keys, formatting values, combining multiple values.   
        #ESO uses "Go" template syntax 
        API_ROOT_PATH: "{{ .API_ROOT_PATH }}"
        LLM_MODEL_ID: "{{ .LLM_MODEL_ID }}"
        EMBEDDING_MODEL_ID: "{{ .EMBEDDING_MODEL_ID }}"
        VECTOR_DB_HOSTNAME: "{{ .VECTOR_DB_HOSTNAME }}"
        INDEX_NAME: "{{ .INDEX_NAME }}"
        VECTOR_TOP_K: "{{ .VECTOR_TOP_K }}"
        RE_RANKED_TOP_K: "{{ .RE_RANKED_TOP_K }}"
        ENABLE_GUARDRAILS: "{{ .ENABLE_GUARDRAILS }}"
        LLM_AS_JUDGE_MODEL_ID: "{{ .LLM_AS_JUDGE_MODEL_ID }}"
        FAITHFULNESS_THRESHOLD: "{{ .FAITHFULNESS_THRESHOLD }}"
        COGNITO_DOMAIN_URI: "{{ .COGNITO_DOMAIN_URI }}"
        CLIENT_ID: "{{ .CLIENT_ID }}"
        CLIENT_SECRET: "{{ .CLIENT_SECRET }}"
        REDIRECT_URI: "{{ .REDIRECT_URI }}"
        

  data:
    - secretKey: API_ROOT_PATH
      remoteRef:
        key: /enterprise-rag/API_ROOT_PATH

    - secretKey: LLM_MODEL_ID
      remoteRef:
        key: /enterprise-rag/LLM_MODEL_ID
    
    - secretKey: EMBEDDING_MODEL_ID
      remoteRef:
        key: /enterprise-rag/EMBEDDING_MODEL_ID

    - secretKey: VECTOR_DB_HOSTNAME
      remoteRef:
        key: /enterprise-rag/VECTOR_DB_HOSTNAME

    - secretKey: INDEX_NAME
      remoteRef:
        key: /enterprise-rag/INDEX_NAME
    
    - secretKey: VECTOR_TOP_K
      remoteRef:
        key: /enterprise-rag/VECTOR_TOP_K

    - secretKey: RE_RANKED_TOP_K
      remoteRef:
        key: /enterprise-rag/RE_RANKED_TOP_K
    
    - secretKey: ENABLE_GUARDRAILS
      remoteRef:
        key: /enterprise-rag/ENABLE_GUARDRAILS
    
    - secretKey: LLM_AS_JUDGE_MODEL_ID
      remoteRef:
        key: /enterprise-rag/LLM_AS_JUDGE_MODEL_ID
    
    - secretKey: FAITHFULNESS_THRESHOLD
      remoteRef:
        key: /enterprise-rag/FAITHFULNESS_THRESHOLD

    - secretKey: COGNITO_DOMAIN_URI
      remoteRef:
        key: /enterprise-rag/COGNITO_DOMAIN_URI
    
    - secretKey: CLIENT_ID
      remoteRef:
        key: /enterprise-rag/CLIENT_ID
    
    - secretKey: CLIENT_SECRET
      remoteRef:
        key: /enterprise-rag/CLIENT_SECRET
    
    - secretKey: REDIRECT_URI
      remoteRef:
        key: /enterprise-rag/REDIRECT_URI


#commenting as currently there are no secrets to be stored in secretmanager
#---
#ESO ExternalSecret for aws secretnamager
#apiVersion: external-secrets.io/v1beta1
#kind: ExternalSecret
#metadata:
#  name: enterprise-rag-secret
#  namespace: enterprise-rag
#  labels:
#    app: enterprise-rag

#spec:
#  refreshInterval: 1h

#  secretStoreRef:
    #this name should match with ClusterSecretStore for aws-secretsmanager
#    name: enterprise-rag-aws-secretsmanager
#    kind: ClusterSecretStore

#  target:
    #this name should match with the one used in "secretRef" in deployment.yaml 
#    name: enterprise-rag-secret

#  data:
#    - secretKey: AWS_ACCESS_KEY_ID
#      remoteRef:
#        key: /enterprise-rag/AWS_ACCESS_KEY_ID

#    - secretKey: AWS_SECRET_ACCESS_KEY
#      remoteRef:
#        key: /enterprise-rag/AWS_SECRET_ACCESS_KEY
        