apiVersion: v1
kind: Service

metadata:
  name: enterprise-rag-service  
  namespace: enterprise-rag
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    #commenting below as creating these were resulting in failure 
    #service.beta.kubernetes.io/aws-load-balancer-type: external
    #service.beta.kubernetes.io/aws-load-balancer-scheme: internal    
    #service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    
  labels:
    app: enterprise-rag    

spec:
  type: LoadBalancer
  ports:
    - targetPort: 8000
      port: 8000      
      protocol: TCP
  selector:
    app: enterprise-rag  