AWSTemplateFormatVersion: '2010-09-09'
Description: Creates NLB ApiGw Integration, APIGateway routes and stage for enterprise-rag

####################### Parameter Block BEGIN #####################
Parameters:
  PrefixName:
    Description: This is the prefix to use for all the resources
    Type: String
    Default: enterprise-rag

  #API Gateway ID
  APIGatewayHttpApi:
    Description: API Gateway ID created by cfn-infra-stack.
    Type: String
  
  VpcLink:
    Description: VPC link created by cfn-infra-stack.    
    Type: String
  
  NLBListenerArn:
    Description: K8s nlb listener created by kubenetes service loadbalancer type
    Type: String

  ApiJwtAuthorizer:
    Description: API gateway jwt authorizer created by cfn-infra-stack
    Type: String
  
      
######################## END  ###################################

################ Resource Block BEGIN ###########################
Resources:
  # -------------------
  # NLB-APIGw integration, APIGw will forward the incoming request 
  # to NLB endpoint using URI specified in IntegrationUri
  # Kubernetes/AWS Load Balancer Controller
  # will create and manage the NLB automatically
  # using this flow: HTTP Request -> API Gw-> VPC Link -> NLB integration -> pods
  # -------------------
  NLBApiGwIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      Description: !Sub ${PrefixName}-NLB-APIGw-integration
      ApiId: !Ref APIGatewayHttpApi
      IntegrationType: HTTP_PROXY
      IntegrationMethod: ANY
      ConnectionType: VPC_LINK
      ConnectionId: !Ref VpcLink
      PayloadFormatVersion: "1.0"      
      IntegrationUri: !Ref NLBListenerArn

  # -------------------
  # Integration for POST /userquery
  # this will send additional parameters obtained from lambda authorizer  
  # -------------------
  UserQueryIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref APIGatewayHttpApi
      IntegrationType: HTTP_PROXY
      IntegrationMethod: ANY
      ConnectionType: VPC_LINK
      ConnectionId: !Ref VpcLink
      PayloadFormatVersion: "1.0"
      IntegrationUri: !Ref NLBListenerArn
      RequestParameters:
        append:header.x-user-id: "$context.authorizer.userId"
        append:header.x-username: "$context.authorizer.username"
  
  # =========================================================================
  # API gateway PUBLIC ROUTES (No Authorizer Enabled)
  # API Gateway forwards to NLB integration specified by NLBApiGwIntegration
  # =========================================================================:   
  
  # -------------------
  # Default 
  # -------------------
  RootRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref APIGatewayHttpApi
      RouteKey: 'ANY /{proxy+}'
      Target: !Join
        - /
        - - integrations
          - !Ref NLBApiGwIntegration

  # -------------------
  # Root GET /
  # -------------------
  RootPathRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref APIGatewayHttpApi
      RouteKey: 'ANY /'
      Target: !Join
        - /
        - - integrations
          - !Ref NLBApiGwIntegration
  # =========================================================================
  # API gateway PRIVATE ROUTES (Authorizer Enabled)
  # =========================================================================:  
  
  # -------------------
  # POST /userquery
  # -------------------
  UserQueryRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref APIGatewayHttpApi
      RouteKey: "POST /userquery"
      AuthorizationType: CUSTOM
      AuthorizerId: !Ref ApiJwtAuthorizer
      Target: !Join
        - /
        - - integrations
          - !Ref UserQueryIntegration

  # -------------------
  # API Stage
  # -------------------
  APIStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref APIGatewayHttpApi
      StageName: "$default"
      AutoDeploy: true
##################### Resource Block END #####################

