# Note: ClusterSecretStore for ESO is known as CRD (Custom Resource Definition) 
# as this is not standard kubernetes resources

#ESO ClusterSecretStore for aws-parameterstore
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  #this name should match with ESO ExternalSecret for aws parameterstore
  name: enterprise-rag-aws-parameterstore
  labels:
    app: enterprise-rag

spec:
  provider:
    aws:
      service: ParameterStore
      region: ap-south-1
      #commenting below as creating auth was causing issue with deployment
      #auth:
      #  jwt:
      #    serviceAccountRef:
      #      name: external-secrets  #serviceaccount of ESO created during installation
      #      namespace: external-secrets #namespace of ESO created during installation

---
#ESO ClusterSecretStore for aws-secretsmanager
#commenting as currently there are no secrets to be stored in aws-secretsmanager
#apiVersion: external-secrets.io/v1
#kind: ClusterSecretStore
#metadata:
  #this name should match with ESO ExternalSecret for aws secretmanager
#  name: enterprise-rag-aws-secretsmanager
#  labels:
#    app: enterprise-rag

#spec:
#  provider:
#    aws:
#      service: SecretsManager
#      region: ap-south-1
#      auth:
#        jwt:
#          serviceAccountRef:
#            name: external-secrets
#            namespace: external-secrets
